"""41: INFO delle metriche (nome chiaro, robustezza, convertibile, frase-istruzione). Usato da classifica.py, esegui_gpt.py, trova_differenze.py."""
# metrica: (nome chiaro, robusta alla risoluzione, convertibile, frase-istruzione / motivo)
# robusta: "si" verificata a 400/600/900 px | "sorgente" esatta dal codice (non dipende dai pixel) | "no" | "non verificata"
INFO = {
 "colore_forte_%": ("colore forte, % pagina", "si", 1, "Un solo colore forte, il corallo #FF654C, pieno, su circa il 5-8% della pagina (mai oltre il 14%): una fascia titolo larga quanto la pagina e alta 50-70 px su 1123, più 1-2 evidenziazioni piccole."),
 "zone_forti": ("zone di colore forte", "si", 1, "Il corallo compare in al massimo 3-4 punti separati (mai più di 6): titolo, caso seguito, risultato."),
 "tinta_dominante_%": ("tinta principale, % del colore", "si", 1, "Almeno il 70% del colore appartiene alla famiglia corallo-pesca; azzurro, verde e giallo solo come tocchi piccoli."),
 "vuoto_terzo_basso_%": ("vuoto nel terzo basso", "si", 0.6, "Il disegno arriva fino in fondo: nel terzo basso della pagina resta vuoto al massimo circa metà dello spazio (lui 25-54%), non un terzo di foglio bianco."),
 "blocco_piu_grande_%": ("blocco più grande, % contenuto", "si", 0.6, "La pagina è fatta di 7-16 gruppi separati da spazio bianco (circa 16 px); nessun gruppo supera circa un terzo del contenuto (lui 16-36%), cioè niente unico pannello o griglia che contiene tutto."),
 "corpo_medio_o_grande_%": ("testo a corpo >= 14 px", "sorgente", 1, "Il testo corrente ha font-size 16-19 px su una pagina larga 794 px (12-14 pt su A4); sotto i 14 px solo note rare (lui: almeno il 74% dei caratteri a 14 px o più)."),
 "testo_su_fondo_pagina_%": ("testo libero sul foglio", "sorgente", 1, "Almeno l'80% del testo sta direttamente sul fondo crema: niente background (bianco o colorato) dietro paragrafi ed etichette, salvo la fascia titolo."),
 "testo_evidenziato_%": ("testo con pillola/casella colorata dietro", "sorgente", 1, "Background colorato aderente al testo (pillola, casella, evidenziatore) al massimo sul 10% del testo: solo poche etichette."),
 "parole_su_prof_%": ("parole rispetto al prof", "sorgente", 1, "Tieni circa il 40-60% delle parole della pagina del docente: le frasi che spiegano il perché restano, il resto diventa etichetta."),
 "parole_in_righe_lunghe_%": ("parole in frasi lunghe", "sorgente", 1, "Circa metà delle parole sta in frasi di almeno 5 parole, su righe larghe almeno un terzo della pagina."),
 "parole": ("numero di parole", "sorgente", 1, "-"),
 "combinazioni_stile_n": ("combinazioni di stile del testo", "sorgente", 1, "Al massimo N combinazioni colore × font × corpo × peso (lui 4-10)."),
 "entropia_stile_bit": ("varietà dello stile (entropia)", "sorgente", 0.6, "-"),
 "combinazioni_forme_n": ("combinazioni di stile delle forme", "sorgente", 1, "-"),
 "forme_linee_%": ("forme che sono linee", "sorgente", 1, "-"),
 "contorni_dritti_%": ("contorni perfettamente dritti", "si", 0.6, "Contorni dei riquadri principali a mano (path irregolari), non rettangoli perfetti."),
 "dentro_riquadri_%": ("area dentro riquadri chiusi", "si", 1, "-"),
 "blocchi_n": ("blocchi separati", "si", 0.6, "-"),
 "riquadri_n": ("riquadri chiusi (numero)", "no", 1, "-"),
 "vuoto_%": ("vuoto totale", "si", 1, "-"),
 "spessore_tratto_‰": ("spessore del tratto", "no", 0.6, "-"),
 "evidenziati_n": ("evidenziati dai pixel (numero)", "no", 1, "sostituita da 'testo con pillola' dal sorgente"),
 "evidenziati_area_%": ("evidenziati dai pixel (area)", "no", 1, "sostituita da 'testo con pillola' dal sorgente"),
 "scuro_%": ("testo/linee scuri", "no", 0.6, "-"),
 "scuro_su_tenue": ("scuro / tenue", "no", 0.6, "-"),
 "tenue_%": ("tenue", "non verificata", 0.6, "-"),
 "pastello_%": ("pastello", "non verificata", 1, "-"),
 "tinte": ("numero di tinte", "non verificata", 1, "-"),
 "forte_alto_%": ("colore forte nel terzo alto", "si", 0, "è solo la fascia del titolo (Gilberto): scartata"),
}
